#!/usr/bin/env bash
get_record_info() {
  local domain=$1
  local subdomain=$2
  local record_type
  local destination

  if [[ -n $subdomain ]]; then
    record_type=$(dig +short -t ANY "$subdomain.$domain" | awk '{ print $4 }')
    destination=$(dig +short "$subdomain.$domain" | awk '{ print $1 }')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
  else
    subdomains=("www" "lb-01" "web-01" "web-02")
    for sub in "${subdomains[@]}"; do
      record_type=$(dig +short -t ANY "$sub.$domain" | awk '{ print $4 }')
      destination=$(dig +short "$sub.$domain" | awk '{ print $1 }')
      echo "The subdomain $sub is a $record_type record and points to $destination"
    done
  fi
}

domain=$1
subdomain=$2

get_record_info "$domain" "$subdomain"
