#!/usr/bin/env bash
# command transfers a file from client to server
# command accepts four parameters

if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  FILE="$1"
  IP="$2"
  USERNAME="$3"
  SSH_KEY="$4"

  if [ -f "$FILE" ]; then
    scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE" "$USERNAME@$IP":~
  else
    echo "File '$FILE' does not exist."
  fi
fi

