#!/usr/bin/env bash
# script installs nginx 
# configures ngix on remote server

apt-get update
apt-get upgrade -y

# Install Nginx
apt-get install nginx -y

# Configure Nginx to listen on port 80
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    location / {
        return 200 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx
killall -9 nginx
nginx

echo "Nginx has been successfully installed and configured!"
