#!/usr/bin/env bash
# script runs comands such as
# installing, configuring
# as well as starting the server
apt-get update
apt-get upgrade -y
apt-get install nginx -y
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    location / {
        return 200 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx
killall -9 nginx
nginx

echo "Nginx has been successfully installed and configured!"
