#!/usr/bin/env bash
# the script sets up new 404 error page
apt-get update

# Installing Nginx
apt-get -y install nginx

# allows Nginx via the firewall
ufw allow 'Nginx HTTP'

# Creates web root directory
mkdir -p /var/www/html/

# command sets permissions for web directory
chmod -R 755 /var/www

# Creates an index.html file
echo 'Hello World!' > /var/www/html/index.html

# Creates custom 404.html file
echo 'Ceci n'est pas une page' > /var/www/html/404.html

# Configures Nginx
SERVER_CONFIG="
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    
    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 http://example.com;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
"

# Overwrites default Nginx config with updated config
echo "$SERVER_CONFIG" > /etc/nginx/sites-available/default

# Restarts Nginx to apply changes
service nginx restart
